{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "756e9d9f-3a78-452b-80bd-b8250076d80e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*** >> THIS IS THE REMOTE SET-UP now :::\n",
      "origin\tgit@github.com:vargasyeriko/_py0ds_git_AIML_ChatBOT_NLPNLU_projects.git (fetch)\n",
      "origin\tgit@github.com:vargasyeriko/_py0ds_git_AIML_ChatBOT_NLPNLU_projects.git (push)\n",
      "\n",
      "*** >> THIS DIREC set to REMOTE avobe  :::\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "'/Users/yerik/_apple_source/PY/JUPY/py0ds/_ds_git_'"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# EMERGENCy rEsET\n",
    "#FIRST  COMMAND + shift +. to see .git hidden\n",
    "# AFTER DELETING REPO DO THIS   :\n",
    "#!git remote remove origin\n",
    "# THEN THIS HAS TO HAVE NOTHING :\n",
    "#!git remote -v\n",
    "\n",
    "### NOW START OVER \n",
    "# 0 # check for REMOTE\n",
    "print('*** >> THIS IS THE REMOTE SET-UP now :::')\n",
    "!git remote -v # if none CREATE REPO in GIT & GET URL: then\n",
    "# \n",
    "# 1 # initiate git REPO --------------- # JUST ONCE\n",
    "#!git init\n",
    "#\n",
    "# 2 # set remote to our project for this DIREC\n",
    "#!git remote add origin git@github.com:vargasyeriko/_py0ds_git_AIML_ChatBOT_NLPNLU_projects.git\n",
    "# \n",
    "# --------------- # THEN stage, commit, push \n",
    "#\n",
    "# check where you are and remember to check .git files\n",
    "import os\n",
    "print('\\n*** >> THIS DIREC set to REMOTE avobe  :::')\n",
    "os.getcwd()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "2031de67-8e29-4aff-8de8-715aafa44b7e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "origin\tgit@github.com:vargasyeriko/_py0ds_git_AIML_ChatBOT_NLPNLU_projects.git (fetch)\n",
      "origin\tgit@github.com:vargasyeriko/_py0ds_git_AIML_ChatBOT_NLPNLU_projects.git (push)\n"
     ]
    }
   ],
   "source": [
    "!git remote -v"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "84618b56-e2b7-4d7c-9a6f-832e3ab2b197",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1 # stage them\n",
    "!git add . \n",
    "# 2 # commit them\n",
    "!git commit -m \"Deleted a few files \"\n",
    "# 3 # push them \n",
    "!git push -u origin main"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6dc48241-8495-443c-8dd9-37555444e859",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dcbfb170-12b3-4d32-a35e-212eb57a9ecd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "0b4b9ffa-c2b1-4bc8-84d0-040f25dcaba0",
   "metadata": {},
   "outputs": [],
   "source": [
    "!git remote -v "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f19612a3-e23b-4998-98fa-23a8bababe97",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3548, in run_code\n",
      "  File \"/var/folders/r1/gtmyxpws2836627xn7_9c5380000gn/T/ipykernel_8977/3060971654.py\", line 14, in <module>\n",
      "    response = requests.post(\n",
      "               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/requests/api.py\", line 115, in post\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/requests/api.py\", line 59, in request\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/requests/sessions.py\", line 589, in request\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/requests/sessions.py\", line 703, in send\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/requests/adapters.py\", line 458, in send\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/requests/adapters.py\", line 261, in cert_verify\n",
      "OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/certifi/cacert.pem\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/pygments/styles/__init__.py\", line 90, in get_style_by_name\n",
      "ModuleNotFoundError: No module named 'pygments.styles.default'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 2142, in showtraceback\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1114, in get_records\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/pygments/styles/__init__.py\", line 92, in get_style_by_name\n",
      "pygments.util.ClassNotFound: Could not find style module 'default', though it should be builtin.\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "tk = \"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\" # 90 days TOKEN \n",
    "\n",
    "tk_1 = tk\n",
    "# Your GitHub username and personal access token\n",
    "username = \"vargasyeriko\"\n",
    "token = tk\n",
    "\n",
    "# Repository details\n",
    "repo_name = \"_ds_git_AIML_ChatBOT_NLPNLU_projects\"\n",
    "repo_description = \" creative Chatbot solutions\" \n",
    "\n",
    "# Create a new repository\n",
    "response = requests.post(\n",
    "    f\"https://api.github.com/user/repos\",\n",
    "    headers={\"Authorization\": f\"token {token}\"},\n",
    "    json={\n",
    "        \"name\": repo_name,\n",
    "        \"description\": repo_description,\n",
    "        # Add more parameters as needed\n",
    "    }\n",
    ")\n",
    "\n",
    "if response.status_code == 201:\n",
    "    print(\"Repository created successfully!\")\n",
    "else:\n",
    "    print(f\"Failed to create repository. Status code: {response.status_code}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "60dde59f-64b9-4047-9213-39ca0d21751b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3548, in run_code\n",
      "  File \"/var/folders/r1/gtmyxpws2836627xn7_9c5380000gn/T/ipykernel_8977/477909178.py\", line 12, in <module>\n",
      "    delete_gt_files(directory)\n",
      "  File \"/var/folders/r1/gtmyxpws2836627xn7_9c5380000gn/T/ipykernel_8977/477909178.py\", line 5, in delete_gt_files\n",
      "    for file in os.listdir(directory):\n",
      "                ^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: ''\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/pygments/styles/__init__.py\", line 90, in get_style_by_name\n",
      "ModuleNotFoundError: No module named 'pygments.styles.default'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 2142, in showtraceback\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/IPython/core/ultratb.py\", line 1114, in get_records\n",
      "  File \"/Users/yerik/miniforge3/envs/ds_env/lib/python3.12/site-packages/pygments/styles/__init__.py\", line 92, in get_style_by_name\n",
      "pygments.util.ClassNotFound: Could not find style module 'default', though it should be builtin.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "def delete_gt_files(directory):\n",
    "    \"\"\"Deletes all .gt files from the specified directory.\"\"\"\n",
    "    for file in os.listdir(directory):\n",
    "        if file.endswith(\".git\"):\n",
    "            os.remove(os.path.join(directory, file))\n",
    "            print(f\"Deleted: {file}\")\n",
    "\n",
    "# To use this function, set the 'directory' variable to the path of your target directory:\n",
    "directory = \"\"\n",
    "delete_gt_files(directory)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43858c24-a921-4e7a-a560-915dde6e0916",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
